run("Leaf (36K)");
run("Set Measurements...", "area mean limit display redirect=None decimal=3");
run("Color Threshold...");
// Color Thresholder 2.0.0-rc-43/1.51k
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");

min[0]=0;
max[0]=100;
filter[0]="pass";
min[1]=0;
max[1]=30;
filter[1]="pass";

// min[2]=0;
// max[2]=194;

selectWindow("2");
resetThreshold();
setAutoThreshold("Default");
getThreshold(min[2],max[2]);
filter[2]="pass";

for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------
run("Analyze Particles...", "summarize");