
run("Set Measurements...", "area mean perimeter area_fraction display redirect=None decimal=3");
//run("Threshold...");
run("Color Threshold...");
selectWindow("Threshold Color");
// Color Thresholder 2.0.0-rc-59/1.51k
// Autogenerated macro, single images only!
min=newArray(3);
max=newArray(3);
filter=newArray(3);
a=getTitle();
run("HSB Stack");
run("Convert Stack to Images");
selectWindow("Hue");
rename("0");
selectWindow("Saturation");
rename("1");
selectWindow("Brightness");
rename("2");
min[0]=0;
max[0]=255;
filter[0]="pass";
min[1]=0;
max[1]=32;
filter[1]="pass";
min[2]=101;
max[2]=255;
filter[2]="pass";
for (i=0;i<3;i++){
  selectWindow(""+i);
  setThreshold(min[i], max[i]);
  run("Convert to Mask");
  if (filter[i]=="stop")  run("Invert");
}
imageCalculator("AND create", "0","1");
imageCalculator("AND create", "Result of 0","2");
for (i=0;i<3;i++){
  selectWindow(""+i);
  close();
}
selectWindow("Result of 0");
close();
selectWindow("Result of Result of 0");
rename(a);
// Colour Thresholding-------------
selectWindow("Recorder");
//setThreshold(255, 255);
run("Make Binary");
//setTool("polygon");
makePolygon(159,94,459,67,500,428,179,452,165,402,150,94);
run("Measure");

